import { KnowledgeGraph, EdgeKind } from './knowledgeGraph';

const KIND_STYLES: Record<EdgeKind, string> = {
  EXTRACTED: '-->|extracted|',
  INFERRED: '-.->|inferred|',
  AMBIGUOUS: '~~>|?|',
};

function sanitizeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_]/g, '_').slice(0, 60);
}

export function renderMermaid(graph: KnowledgeGraph, opts: { maxNodes?: number } = {}): string {
  const maxNodes = opts.maxNodes ?? 50;
  const nodes = graph.nodes.slice(0, maxNodes);
  const nodeIds = new Set(nodes.map(n => n.id));
  const edges = graph.edges.filter(e => nodeIds.has(e.from) && nodeIds.has(e.to));

  const lines: string[] = ['graph LR'];
  for (const n of nodes) {
    const id = sanitizeId(n.id);
    const label = n.label.replace(/"/g, "'").slice(0, 40);
    const shape = n.type === 'file' ? `["${label}"]` : `(${label})`;
    lines.push(`  ${id}${shape}`);
  }
  for (const e of edges) {
    const arrow = KIND_STYLES[e.kind] ?? '-->';
    lines.push(`  ${sanitizeId(e.from)} ${arrow} ${sanitizeId(e.to)}`);
  }
  return lines.join('\n');
}

export function renderMermaidHtml(mermaidSource: string, title = 'Knowledge Graph'): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${title}</title>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<style>
  body { font-family: system-ui, sans-serif; padding: 20px; background: #1e1e1e; color: #ddd; }
  .mermaid { background: #2d2d2d; padding: 20px; border-radius: 8px; }
  h1 { color: #4fc3f7; }
  .meta { color: #888; font-size: 0.9em; }
</style>
</head>
<body>
  <h1>🧬 ${title}</h1>
  <div class="meta">Generated by INI Brain AI Universal · ${new Date().toLocaleString()}</div>
  <div class="mermaid">
${mermaidSource}
  </div>
  <script>mermaid.initialize({ startOnLoad: true, theme: 'dark' });</script>
</body>
</html>`;
}
