import { BrainData, FileRecord } from './types';

/**
 * InsightBuilder turns the brain snapshot (file index + dependency graph) into
 * human/AI-readable understanding documents — without needing an LLM.
 * Adapted to the universal BrainData shape (files map + incoming/outgoing).
 */

export interface ExplainResult {
  found: boolean;
  path: string;
  markdown: string;
}

export interface ImpactResult {
  changedFiles: string[];
  mappedFiles: string[];
  unmappedFiles: string[];
  affectedFiles: string[];
  risk: 'low' | 'medium' | 'high';
  markdown: string;
}

export class InsightBuilder {
  buildOnboarding(data: BrainData): string {
    const files = Object.values(data.files);
    const lines: string[] = [];

    lines.push('# Project Onboarding Guide');
    lines.push('');
    lines.push(`> Generated by INI Brain AI on ${new Date().toISOString()}`);
    lines.push('');
    lines.push('| | |');
    lines.push('|---|---|');
    lines.push(`| **Languages** | ${formatLanguages(data.projectMap.languages)} |`);
    lines.push(`| **Files** | ${data.projectMap.totalFiles} indexed |`);
    lines.push('');

    const hotspots = topByIncoming(files, data.dependencies.incoming, 10);
    if (hotspots.length) {
      lines.push('## Start Here (most depended-on files)');
      lines.push('');
      lines.push('These files are imported by the most modules — understand them first:');
      lines.push('');
      for (const { record, incoming } of hotspots) {
        const exportsHint = record.exports.length ? `; exports: ${record.exports.slice(0, 6).join(', ')}` : '';
        lines.push(`- \`${record.path}\` — used by ${incoming} file(s)${exportsHint}`);
      }
      lines.push('');
    }

    const entryPoints = topEntryPoints(files, data.dependencies, 6);
    if (entryPoints.length) {
      lines.push('## Likely Entry Points');
      lines.push('');
      for (const record of entryPoints) {
        const out = data.dependencies.outgoing[record.path]?.length ?? 0;
        lines.push(`- \`${record.path}\` — wires together ${out} module(s)`);
      }
      lines.push('');
    }

    const complex = [...files]
      .sort((a, b) => (b.imports.length + b.size / 1000) - (a.imports.length + a.size / 1000))
      .slice(0, 8);
    if (complex.length) {
      lines.push('## Complexity Hotspots');
      lines.push('');
      lines.push('| File | Imports | Size (KB) |');
      lines.push('|------|---------|-----------|');
      for (const f of complex) {
        lines.push(`| \`${f.path}\` | ${f.imports.length} | ${(f.size / 1024).toFixed(1)} |`);
      }
      lines.push('');
    }

    if (data.projectMap.coreFiles?.length) {
      lines.push('## Core Files');
      lines.push('');
      for (const cf of data.projectMap.coreFiles.slice(0, 12)) {
        lines.push(`- \`${cf}\``);
      }
      lines.push('');
    }

    return lines.join('\n');
  }

  buildExplain(data: BrainData, relPath: string): ExplainResult {
    const normalized = relPath.replace(/\\/g, '/').replace(/^\.\//, '');
    const record = data.files[normalized];
    if (!record) {
      return { found: false, path: normalized, markdown: `# Not Found\nFile \`${normalized}\` is not in the brain index.` };
    }
    const incoming = data.dependencies.incoming[normalized] || [];
    const outgoing = data.dependencies.outgoing[normalized] || [];
    const lines: string[] = [];
    lines.push(`# ${record.path}`);
    lines.push('');
    lines.push(`- Language: ${record.language}`);
    lines.push(`- Size: ${(record.size / 1024).toFixed(1)} KB`);
    if (record.exports.length) lines.push(`- Exports: ${record.exports.slice(0, 12).join(', ')}`);
    if (record.classes?.length) lines.push(`- Classes: ${record.classes.slice(0, 12).join(', ')}`);
    if (record.functions?.length) lines.push(`- Functions: ${record.functions.slice(0, 12).join(', ')}`);
    if (record.summary) {
      lines.push('');
      lines.push('## Summary');
      lines.push(record.summary);
    }
    lines.push('');
    lines.push('## Depends On');
    if (outgoing.length) {
      for (const dep of outgoing.slice(0, 25)) lines.push(`- \`${dep}\``);
    } else {
      lines.push('- (no resolved internal imports)');
    }
    lines.push('');
    lines.push('## Used By');
    if (incoming.length) {
      for (const dep of incoming.slice(0, 25)) lines.push(`- \`${dep}\``);
    } else {
      lines.push('- (no internal dependents)');
    }
    return { found: true, path: normalized, markdown: lines.join('\n') };
  }

  buildImpact(data: BrainData, changed: string[]): ImpactResult {
    const norm = changed.map(c => c.replace(/\\/g, '/').replace(/^\.\//, ''));
    const mapped: string[] = [];
    const unmapped: string[] = [];
    for (const c of norm) (data.files[c] ? mapped : unmapped).push(c);

    const affected = new Set<string>();
    const queue = [...mapped];
    while (queue.length) {
      const cur = queue.shift()!;
      const dependents = data.dependencies.incoming[cur] || [];
      for (const d of dependents) {
        if (!affected.has(d) && !mapped.includes(d)) {
          affected.add(d);
          queue.push(d);
        }
      }
    }

    const total = affected.size;
    const risk: ImpactResult['risk'] = total > 20 ? 'high' : total > 6 ? 'medium' : 'low';

    const lines: string[] = [];
    lines.push('# Change Impact Analysis');
    lines.push('');
    lines.push(`- Changed files: ${mapped.length} mapped, ${unmapped.length} unmapped`);
    lines.push(`- Affected (transitive): ${total}`);
    lines.push(`- Risk: **${risk.toUpperCase()}**`);
    lines.push('');
    if (mapped.length) {
      lines.push('## Changed (in index)');
      for (const c of mapped) lines.push(`- \`${c}\``);
      lines.push('');
    }
    if (unmapped.length) {
      lines.push('## Unmapped (not yet indexed)');
      for (const c of unmapped) lines.push(`- \`${c}\``);
      lines.push('');
    }
    if (affected.size) {
      lines.push('## Transitively Affected Files');
      for (const f of [...affected].sort().slice(0, 60)) lines.push(`- \`${f}\``);
      if (affected.size > 60) lines.push(`- ... and ${affected.size - 60} more`);
    }

    return { changedFiles: norm, mappedFiles: mapped, unmappedFiles: unmapped, affectedFiles: [...affected], risk, markdown: lines.join('\n') };
  }
}

function formatLanguages(langs: Record<string, number>): string {
  return Object.entries(langs)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([k, v]) => `${k} (${v})`)
    .join(', ') || 'unknown';
}

function topByIncoming(files: FileRecord[], incomingMap: Record<string, string[]>, n: number) {
  return files
    .map(record => ({ record, incoming: incomingMap[record.path]?.length ?? 0 }))
    .filter(x => x.incoming > 0)
    .sort((a, b) => b.incoming - a.incoming)
    .slice(0, n);
}

function topEntryPoints(files: FileRecord[], deps: { incoming: Record<string, string[]>; outgoing: Record<string, string[]> }, n: number): FileRecord[] {
  return [...files]
    .map(f => ({ f, out: deps.outgoing[f.path]?.length ?? 0, inc: deps.incoming[f.path]?.length ?? 0 }))
    .filter(x => x.out >= 3 && x.inc <= 1)
    .sort((a, b) => b.out - a.out)
    .slice(0, n)
    .map(x => x.f);
}
